#!/usr/bin/env bash
#
while IFS=: read -r username _ GROUP_ID _ HOME_DIRECTORY _ COMMAND/SHELL _ USER ID _ PASSWORD _ USER ID INFO; do
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER ID INFO"
done 
